### ISSUE TITLE
Test on MSK TOIL 3.21

### ISSUE THREAD

**Issue by rhshah** [msk-access/nucleo#102]

**Comment by rhshah** [comment]
- Ran test worked fine with regular repo structure.
- cwltool packing does not work with this version of cwltool in the toil
Here is the error:
```bash
git clone --recursive --branch 0.1.2 https://github.com/msk-access/fastq_to_bam.git
source /home/accessbot/miniconda3/bin/activate
conda activate ACCESS_1.3.40
cd fastq_to_bam
cwltool --debug --pack fast_to_bam.cwl
```
Here is log:
```
$ cwltool --debug --pack fastq_to_bam.cwl
/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/cwltool/__init__.py:17: CWLToolDeprecationWarning:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
Please upgrade your Python as the Python 2.7 version of cwltool won't be
maintained after that date.

  """,  category=CWLToolDeprecationWarning)
INFO /home/accessbot/miniconda3/envs/ACCESS_1.3.40/bin/cwltool 1.0.20190906054215
INFO Resolved 'fastq_to_bam.cwl' to 'file:///juno/work/bergerm1/bergerlab/shahr2/test/fastq_to_bam_test/fastq_to_bam/fastq_to_bam.cwl'
WARNING https://schema.org/docs/!DOCTYPE html does not look like a valid URI, trying to serialize this will break.
WARNING html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" does not look like a valid URI, trying to serialize this will break.
/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/rdflib/plugins/parsers/structureddata.py:30: UserWarning: html5lib not found! RDFa and Microdata parsers will not be available.
  'parsers will not be available.')
Could not load extension schema https://schema.org/docs/schema_org_rdfa.html: html5lib is not installed, cannot use RDFa and Microdata parsers.
ERROR Tool definition failed validation:
[Errno 2] No such file or directory: '/juno/work/bergerm1/bergerlab/shahr2/test/fastq_to_bam_test/fastq_to_bam/subworkflows/calculate_apply_bqsr.cwl'
Traceback (most recent call last):
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/cwltool/main.py", line 678, in main
    stdout.write(print_pack(loadingContext.loader, processobj, uri, metadata))
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/cwltool/main.py", line 468, in print_pack
    packed = pack(document_loader, processobj, uri, metadata)
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/cwltool/pack.py", line 139, in pack
    find_run(processobj, loadref, runs)
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/cwltool/pack.py", line 48, in find_run
    find_run(s, loadref, runs)
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/cwltool/pack.py", line 41, in find_run
    find_run(s, loadref, runs)
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/cwltool/pack.py", line 46, in find_run
    find_run(loadref(None, d["run"]), loadref, runs)
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/cwltool/pack.py", line 48, in find_run
    find_run(s, loadref, runs)
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/cwltool/pack.py", line 41, in find_run
    find_run(s, loadref, runs)
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/cwltool/pack.py", line 46, in find_run
    find_run(loadref(None, d["run"]), loadref, runs)
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/cwltool/pack.py", line 133, in loadref
    return document_loader.resolve_ref(uri, base_url=base)[0]
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 747, in resolve_ref
    doc = self.fetch(doc_url, inject_ids=(not mixin))
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 1212, in fetch
    text = self.fetch_text(url)
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 213, in fetch_text
    raise_from(ValidationException(Text(err)), err)
  File "/home/accessbot/miniconda3/envs/ACCESS_1.3.40/lib/python2.7/site-packages/future/utils/__init__.py", line 456, in raise_from
    raise e
ValidationException: [Errno 2] No such file or directory: '/juno/work/bergerm1/bergerlab/shahr2/test/fastq_to_bam_test/fastq_to_bam/subworkflows/calculate_apply_bqsr.cwl'
```

**Comment by rhshah** [comment]
@ionox0  and @nikhil if you have any insights that will be great
