### ISSUE TITLE
completed permanentFail

### ISSUE THREAD

**Issue by AdilyAid** [msk-access/nucleo#170]
* fastq_to_bam version: 3.0.4
* Python version: 3.9
* Operating System: linux

Hello, 
I run `cwltool --make-template nucleo.cwl` and got the next messages:

```
...
INFO	Mon Aug 08 13:08:00 UTC 2022	Processing chromosome chunk: chr6_KI270798v1_alt_1_271782
INFO	Mon Aug 08 13:08:00 UTC 2022	Processing chromosome chunk: chr6_KB021644v2_alt_1_185823
INFO	Mon Aug 08 13:08:00 UTC 2022	Clock time in Chromosome: chr5_KI270795v1_alt_1_131892: 0
INFO	Mon Aug 08 13:08:00 UTC 2022	Processing chromosome chunk: chr7_KI270809v1_alt_1_209586
WARNING [job abra2_2_22] completed permanentFail
WARNING [step abra2_2_22] completed permanentFail
WARNING [step indel_realignment] completed permanentFail
WARNING [step uncollapsed_bam_generation] completed permanentFail
...
WARNING Final process status is permanentFail
```
Why abra2 failed? 

Thank you for your help,
Adily

**Comment by rhshah** [comment]
I am not sure if I understand `cwltool --make-template nucleo.cwl` will not run anything but just try to generate the input file. You probably meant to post the correct input.

**Comment by AdilyAid** [comment]
Sorry, I meant to post the pipeline command:
 `cwltool nucleo.cwl inputs_test.yaml`

**Comment by AdilyAid** [comment]
Hello, I have change some names of the files at the input.yaml, and now I got the next error:

```
WARNING [job gatk_merge_bam_alignment_4_1_8_0] Skipping Docker software container '--memory' limit despite presence of ResourceRequirement with ramMin and/or ramMax setting. Consider running with --strict-memory-limit for increased portability assurance.
12:04:23.452 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk/gatk-package-4.1.8.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Tue Aug 09 12:04:23 GMT 2022] MergeBamAlignment --UNMAPPED_BAM /var/lib/cwl/stgece03dd8-3c3d-4973-9c5e-2c2e1a879ccc/gatk_uncollapsed_merged.sam --ALIGNED_BAM /var/lib/cwl/stga7a49e8b-fc2e-49ce-97cb-6828b0f9e756/UBG_picard_uncollapsed.bam --OUTPUT UBG_gatk_uncollapsed_merged.bam --TMP_DIR /tmp --VALIDATION_STRINGENCY LENIENT --CREATE_INDEX true --REFERENCE_SEQUENCE /var/lib/cwl/stg5e54b558-ebc3-410a-b7bf-5fadab38d306/hg38.fa --ADD_PG_TAG_TO_READS true --PAIRED_RUN true --CLIP_ADAPTERS true --IS_BISULFITE_SEQUENCE false --ALIGNED_READS_ONLY false --MAX_INSERTIONS_OR_DELETIONS 1 --ATTRIBUTES_TO_REVERSE OQ --ATTRIBUTES_TO_REVERSE U2 --ATTRIBUTES_TO_REVERSE_COMPLEMENT E2 --ATTRIBUTES_TO_REVERSE_COMPLEMENT SQ --READ1_TRIM 0 --READ2_TRIM 0 --ALIGNER_PROPER_PAIR_FLAGS false --SORT_ORDER coordinate --PRIMARY_ALIGNMENT_STRATEGY BestMapq --CLIP_OVERLAPPING_READS true --HARD_CLIP_OVERLAPPING_READS false --INCLUDE_SECONDARY_ALIGNMENTS true --ADD_MATE_CIGAR true --UNMAP_CONTAMINANT_READS false --MIN_UNCLIPPED_BASES 32 --MATCHING_DICTIONARY_TAGS M5 --MATCHING_DICTIONARY_TAGS LN --UNMAPPED_READ_STRATEGY DO_NOT_CHANGE --VERBOSITY INFO --QUIET false --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
Aug 09, 2022 12:04:23 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
[Tue Aug 09 12:04:23 GMT 2022] Executing as ?@9985ec23afc9 on Linux 5.15.0-43-generic amd64; OpenJDK 64-Bit Server VM 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.1.8.0
INFO	2022-08-09 12:04:23	SamAlignmentMerger	Processing SAM file(s): [/var/lib/cwl/stga7a49e8b-fc2e-49ce-97cb-6828b0f9e756/UBG_picard_uncollapsed.bam]
[Tue Aug 09 12:04:31 GMT 2022] picard.sam.MergeBamAlignment done. Elapsed time: 0.14 minutes.
Runtime.totalMemory()=1576534016
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
java.lang.ArrayIndexOutOfBoundsException: 90
	at htsjdk.samtools.util.SequenceUtil.calculateMdAndNmTags(SequenceUtil.java:982)
	at picard.sam.AbstractAlignmentMerger.fixNmMdAndUq(AbstractAlignmentMerger.java:611)
	at picard.sam.AbstractAlignmentMerger.mergeAlignment(AbstractAlignmentMerger.java:586)
	at picard.sam.SamAlignmentMerger.mergeAlignment(SamAlignmentMerger.java:181)
	at picard.sam.MergeBamAlignment.doWork(MergeBamAlignment.java:366)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at org.broadinstitute.hellbender.Main.main(Main.java:292)
Using GATK jar /gatk/gatk-package-4.1.8.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx15G -jar /gatk/gatk-package-4.1.8.0-local.jar MergeBamAlignment --TMP_DIR /tmp --CREATE_INDEX --REFERENCE_SEQUENCE /var/lib/cwl/stg5e54b558-ebc3-410a-b7bf-5fadab38d306/hg38.fa --UNMAPPED_BAM /var/lib/cwl/stgece03dd8-3c3d-4973-9c5e-2c2e1a879ccc/gatk_uncollapsed_merged.sam --VALIDATION_STRINGENCY LENIENT -O UBG_gatk_uncollapsed_merged.bam --ALIGNED_BAM /var/lib/cwl/stga7a49e8b-fc2e-49ce-97cb-6828b0f9e756/UBG_picard_uncollapsed.bam
WARNING [job gatk_merge_bam_alignment_4_1_8_0] completed permanentFail
WARNING [step gatk_merge_bam_alignment_4_1_8_0] completed permanentFail
WARNING [step uncollapsed_bam_generation] completed permanentFail

```
What can cause the java exception?
I would appreciate your reference also to the previous question.

Thank you in advance,
Adily

**Comment by rhshah** [comment]
> Sorry, I meant to post the pipeline command: `cwltool nucleo.cwl inputs.yaml`
> 
> Can it be a cpu/memory issue? I give it a very small fastq files - each of them contain only 50 reads

Maybe as its difficult for me to say about the errors as we have not seen them. We have some test data here https://drive.google.com/file/d/1GtT8jsBGwRoQC-5wHh06r8RFkiFBuirp/view if you want to use it.

**Comment by AdilyAid** [comment]
I guess the first problem was a cpu issue. 
The second was related to the extensions of some of the input files at the input.yaml - the test data was help for that.
The pipeline succeeded. Thank you!
